### ISSUE TITLE
shouldn't posn be non parametric?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-2htdp-typed#1]
since you can't define it properly as a parametric type, shouldn't you just use

``` racket
(require/typed/provide
 lang/posn
 [#:opaque Posn posn?]
 [make-posn [Real Real -> Posn]]
 [posn-x [Posn -> Real]]
 [posn-y [Posn -> Real]])
```

By the way with the parametric type I get errors like this:

``` racket
> (define p ((inst make-posn Byte) 1 2))
> p
- : htdp:posn
(posn #<A7> #<A7>) ; um, what?
> (posn-x p)
. . posn-x: broke its contract
  promised: A10
  produced: #<A7>
  in: the range of
      (parametric->/c
       (A10)
       (->* (g12) () (values A10)))
  contract from: (interface for posn-x)
  blaming: (interface for posn-x)
   (assuming the contract is correct)
  at: <pkgs>/2htdp-typed/typed/lang/posn.rkt:15.2
```

And anyway if you can figure out how to make it parametric properly, shouldn't it be parametric over 2 type variables instead of 1?

**Comment by lexi-lambda** [comment]
Hmm, this is interesting, I didn't realize how broken this is. I'll take a look when I get around to it, but @samth, could you explain why this typechecks but doesn't work at all? Where are those strange contract errors coming from? Why `#<A7>`?

**Comment by AlexKnauth** [comment]
In case it helps, here's a simpler program that fails in the same way:

``` racket
#lang typed/racket
(require/typed racket/function [identity (All (X) X -> Number)])
(identity 1)
```

It gives this error message:

```
. . identity: broke its contract
  promised: Number
  produced: #<X3>
  in: the range of
      (parametric->/c
       (X3)
       (->* (X3) () (values g5)))
  contract from: (interface for identity)
  blaming: (interface for identity)
   (assuming the contract is correct)
  at: /Users/Alex/Documents/DrRacket/untitled-folder/typed.rkt:2.32
```

**Comment by AlexKnauth** [comment]
See also http://docs.racket-lang.org/reference/parametric-contracts.html#%28def._%28%28lib._racket%2Fcontract%2Fparametric..rkt%29._new-~e2~88~80%2Fc%29%29

**Comment by lexi-lambda** [comment]
Removed. I may revisit this later if I can come up with a solution.
